generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Mode3
    theme:                 admin
    css:                   backend

    non_verbose_templates: true
    with_show:             false
    singular:              mode3
    plural:                mode3s
    route_prefix:          mode3
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   admin-gen   #setting the css to a placeholder

    config:
      actions:
        _new: { label: "Create a new Mode 3 SSID" }
      fields:  ~
      list:
        title: List of Mode 3 SSIDs
        display: [id, =name, _config, vlan, broadcast, radius_auth_ip, radius_acct_ip, vpn_auth_server, vpn_data_server, _dhcp_servers]
      filter:  ~
      form:    ~
      edit:
        title: Edit Mode 3 SSID
      new:
        title: Create Mode 3 SSID
