# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sf_admin_dash:
    web_dir: /sfAdminDashPlugin
    image_dir: /sfAdminDashPlugin/images/icons/
    default_image: config.png
    resize_mode: thumbnail
    site: CUGAR Server admin
    include_path: true
    include_jquery_no_conflict: false
    logout: true
    login_route: '@sf_guard_signin'
    logout_route: '@sf_guard_signout'

    items:
      Config:
        url: config
      Devices:
        url: device
      SSIDs:
        url: ssid

    categories:
      Mode 3:
        items:
          DHCP Relay:
            url: dhcp_server
          Certificates:
            url: mode3_certificate
      User Management:
        items:
          Users:
            url: sf_guard_user
          Groups:
            url: sf_guard_group
          Permissions:
            url: sf_guard_permission

