device_log:
  class: sfDoctrineRouteCollection
  options:
    model:                DeviceLog
    module:               device_log
    prefix_path:          /device_log
    column:               id
    with_wildcard_routes: true

config:
  class: sfDoctrineRouteCollection
  options:
    model:                Config
    module:               config
    prefix_path:          /config
    column:               id
    with_wildcard_routes: true

device:
  class: sfDoctrineRouteCollection
  options:
    model:                Device
    module:               device
    prefix_path:          /device
    column:               id
    with_wildcard_routes: true

dhcp_server:
  class: sfDoctrineRouteCollection
  options:
    model:                DhcpServer
    module:               dhcp_server
    prefix_path:          /dhcp_server
    column:               id
    with_wildcard_routes: true

mode1:
  class: sfDoctrineRouteCollection
  options:
    model:                Mode1
    module:               mode1
    prefix_path:          /mode1
    column:               id
    with_wildcard_routes: true

mode2:
  class: sfDoctrineRouteCollection
  options:
    model:                Mode2
    module:               mode2
    prefix_path:          /mode2
    column:               id
    with_wildcard_routes: true

mode3:
  class: sfDoctrineRouteCollection
  options:
    model:                Mode3
    module:               mode3
    prefix_path:          /mode3
    column:               id
    with_wildcard_routes: true

mode3_certificate:
  class: sfDoctrineRouteCollection
  options:
    model:                Mode3Certificate
    module:               mode3_certificate
    prefix_path:          /mode3_certificate
    column:               id
    with_wildcard_routes: true

device_config_post:
  url: /getconfig
  requirements: { cert_name: \s+, cert_name_check: \s+ }
  param: { module: deviceInterface, action: getXml, sf_format: xml }

device_config_get:
  url: /getconfig/:cert_name
  requirements: { cert_name_check: \s+ }
  param: { module: deviceInterface, action: getXml, sf_format: xml }

device_error_post:
  url: /posterror
  requirements: { sf_method: [post], cert_name: \s+, cert_name_check: \s+ }
  param: { module: deviceInterface, action: postError, sf_format: xml }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
