Config:
  columns:
    id: { type: integer(4), unsigned: true, autoincrement: true, primary: true }
    name: { type: string(50), minlength: 1, notnull: true }
    update_server: { type: string(255), notnull: true, minlength: 3 }
    wireless_channel: { type: int(2), minlength: 1, unsigned: true, range: [1, 13] }
    wireless_mode:
      type: enum
      values: [auto, B, G, N]
      default: auto
      notnull: true
    
Device:
  columns:
    id: { type: integer(4), unsigned: true, autoincrement: true, primary: true }
    name: { type: string(50), minlength: 5, notnull: true }
    config_id: { type: integer(4), unsigned: true, notnull: true }
  indexes:
    cert_name:
      fields: [name]
      type: unique
  relations:
    Config:
      class: Config
      local: config_id
      foreign: id
      foreignAlias: Devices
      type: one

DeviceLog:
  columns:
    id: { type: integer(4), unsigned: true, autoincrement: true, primary: true }
    device_id: { type: integer(4), unsigned: true, notnull: true }
    time: { type: timestamp, notnull: true }
    description: { type: text, notnull: true }
  relations:
    Device:
      class: Device
      local: device_id
      foreign: id
      foreignAlias: Logs
      type: one

DhcpServer:
  columns:
    id: { type: integer(4), unsigned: true, autoincrement: true, primary: true }
    mode3_id: { type: integer(4), unsigned: true, notnull: true}
    ip:
      type: string(15)
      ip: true
  relations:
    Mode3:
      class: Mode3
      local: mode3_id
      foreign: id
      foreignAlias: DhcpServers
      type: one

Ssid:
  columns:
    id: { type: integer(4), unsigned: true, autoincrement: true, primary: true }
    name: { type: string(32), notnull: true, minlength: 1, nospace: true, regexp: '/^[a-zA-Z0-9_]+$/' }
#    mode:
#      type: enum
#      values: [1, 2, 3]
#      default: 1
#      notnull: true
    wpa_mode:
      type: enum
      values: [wpa, wpa2, off]
      default: wpa2
      notnull: true
    vlan: { type: integer(2), notnull: false, range: [1, 4096] }
    broadcast: { type: boolean, notnull: true, default: true }
    passphrase: { type: string(255) }
    group_rekey_interval: { type: integer(4), notnull: true, default: 600 }
    strict_rekey: { type: boolean, notnull: true, default: true }

RadiusSsid:
  inheritance:
    type:          concrete
    extends:       Ssid
  columns:
    retry_interval: { type: integer(4), unsigned: true, notnull: true, default: 600 }
    own_ip: { type: string(15), ip: true, notnull: true }
    nas_identifier: { type: string(48), notnull: true, minlength: 1 }
    radius_auth_ip: { type: string(15), ip: true, notnull: true }
    radius_auth_port: { type: integer(3), unsigned: true, notnull: true, range: [1, 65535] }
    radius_auth_shared_secret: { type: string(255), notnull: true, minlength: 1}
    radius_acct_ip: { type: string(15), ip: true, notnull: true }
    radius_acct_port: { type: integer(3), unsigned: true, notnull: true, range: [1, 65535] }
    radius_acct_shared_secret: { type: string(255), notnull: true, minlength: 1}
    radius_acct_interim_interval: { type: integer(3), unsigned: true, notnull: true, range: [1], default: 600 }

Mode1:
  inheritance:
    type:          concrete
    extends:       Ssid
  columns:
    config_id: { type: integer(4), unsigned: true, notnull: true }
  relations:
    Config:
      class: Config
      local: config_id
      foreign: id
      foreignAlias: Mode1s
      type: one

Mode2:
  inheritance:
    type:          concrete
    extends:       RadiusSsid
  columns:
    config_id: { type: integer(4), unsigned: true, notnull: true }
    file_name: { type: string(255), notnull: true, minlength: 4 }
  relations:
    Config:
      class: Config
      local: config_id
      foreign: id
      foreignAlias: Mode2s
      type: one

Mode3:
  inheritance:
    type:          concrete
    extends:       RadiusSsid
  columns:
    config_id: { type: integer(4), unsigned: true, notnull: true }
    dhcp_hw_interface: {type: string(5), notnull: true, minlength: 3 }
    vpn_auth_server: { type: string(255), notnull: true, minlength: 4 }
    vpn_auth_port: { type: integer(3), unsigned: true, notnull: true, range: [1, 65535] }
    vpn_auth_cipher:
      type: enum
      values: [DES-CBC, AES-128-CBC, AES-192-CBC, AES-256-CBC, BF-CBC]
      default: AES-128-CBC
      notnull: true
    vpn_auth_compression: { type: boolean, notnull: true, default: false }
    vpn_data_server: { type: string(255), notnull: true, minlength: 4 }
    vpn_data_port: { type: integer(3), unsigned: true, notnull: true, range: [1, 65535] }
    vpn_data_cipher:
      type: enum
      values: [DES-CBC, AES-128-CBC, AES-192-CBC, AES-256-CBC, BF-CBC]
      default: AES-128-CBC
      notnull: true
    vpn_data_compression: { type: boolean, notnull: true, default: false }
  relations:
    Config:
      class: Config
      local: config_id
      foreign: id
      foreignAlias: Mode3s
      type: one

Mode3Certificate:
  columns:
    id: { type: integer(4), unsigned: true, autoincrement: true, primary: true }
    mode3_id: { type: integer(4), unsigned: true, notnull: true }
    device_id: { type: integer(4), unsigned: true, notnull: true }
    public_key_name: { type: string(255), notnull: true, minlength: 5 }
    public_key: {type: string, notnull: true }
    private_key_name: { type: string(255), notnull: true, minlength: 5 }
    private_key: {type: string, notnull: true }
    cert_of_authority: {type: string, notnull: true }
  indexes:
    unique_mode3_device:
      fields: [mode3_id, device_id]
      unique: true
  relations:
    Mode3:
      class: Mode3
      local: mode3_id
      foreign: id
      foreignAlias: Certificates
      type: one
    Device:
      class: Device
      local: device_id
      foreign: id
      foreignAlias: Certificates
      type: one

