generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Mode2
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              mode2
    plural:                mode2s
    route_prefix:          mode2
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   admin-gen   #setting the css to a placeholder

    config:
      actions:
        _new: { label: "Create a new Mode 2 SSID" }
      fields:  ~
      list:
        title: List of Mode 2 SSIDs
        display: [id, =name, _config, vlan, broadcast]
      filter:  ~
      form:
        display:
          Config:                       [config_id]
          SSID settings:                [name, broadcast, vlan]
          Radius authentication server: [retry_interval, own_ip, nas_identifier, radius_auth_ip, radius_auth_port, radius_auth_shared_secret]
          Radius accounting server:     [radius_acct_ip, radius_acct_port, radius_acct_shared_secret, radius_acct_interim_interval]
      edit:
        title: Edit Mode 2 SSID
      new:
        title: Create Mode 2 SSID
